<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-FI8UJG3" failures="6" tests="33" name="Test" time="6.521" errors="0" timestamp="2022-03-31T15:25:55 IST">
  <testcase classname="testNG.TestNG_DependOn" name="EmailLogin" time="0.008"/>
  <testcase classname="testNG.TestNG_DependOn" name="ComposeEmail" time="0.003"/>
  <testcase classname="testNG.TestNG_DependOn" name="LogoutAccount" time="0.004"/>
  <testcase classname="testNG.TestNG_Enable" name="Test1" time="0.013"/>
  <testcase classname="testNG.TestNG_Enable" name="Test3" time="0.006"/>
  <testcase classname="testNG.TestNG_Enable" name="Test5" time="0.002"/>
  <testcase classname="testNG.TestNG_TimeOut" name="Test1" time="0.002"/>
  <testcase classname="testNG.TestNG_TimeOut" name="Test2" time="0.003"/>
  <testcase classname="testNG.TestNG_TimeOut" name="Test3" time="1.022">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG.TestNG_TimeOut.Test3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG.TestNG_TimeOut.Test3() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="testNG.TestNG_TimeOut" name="Test4" time="0.005"/>
  <testcase classname="testNG.TestNG_TimeOut" name="Test5" time="1.014">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG.TestNG_TimeOut.Test5() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG.TestNG_TimeOut.Test5() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
  <testcase classname="testNG.TestNG_InvocationCount" name="EmailLogin" time="0.006"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.003"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.003"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.003"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.003"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.004"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.003"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.001"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.002"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.004"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="ComposeEmail" time="0.002"/>
  <testcase classname="testNG.TestNG_InvocationCount" name="LogoutAccount" time="0.002"/>
  <testcase classname="testNG.FailedTest" name="Test1" time="1.018">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG.FailedTest.Test1() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG.FailedTest.Test1() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="testNG.FailedTest" name="Test2" time="0.017"/>
  <testcase classname="testNG.FailedTest" name="Test3" time="1.019">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG.FailedTest.Test3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG.FailedTest.Test3() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="testNG.FailedTest" name="Test4" time="1.008">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG.FailedTest.Test4() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG.FailedTest.Test4() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase classname="testNG.FailedTest" name="Test5" time="1.016">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG.FailedTest.Test5() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG.FailedTest.Test5() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
  <testcase classname="testNG.TestNG_Priority" name="CreateAccount" time="0.004"/>
  <testcase classname="testNG.TestNG_Priority" name="EditAccount" time="0.002"/>
  <testcase classname="testNG.TestNG_Priority" name="DeleteAccount" time="0.003"/>
  <testcase classname="testNG.TestNG_Annotationns" name="TC1" time="0.002"/>
  <testcase classname="testNG.TestNG_Annotationns" name="TC2" time="0.003"/>
  <testcase classname="testNG.TestNG_Enable" name="Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNG.TestNG_Enable" name="Test4" time="0.0">
    <ignored/>
  </testcase> <!-- Test4 -->
</testsuite> <!-- Test -->
